# Generated by Django 5.0.6 on 2024-06-21 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área de Interesse',
                'verbose_name_plural': 'Áreas de Interesse',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=255, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=255, verbose_name='CPF')),
                ('rg', models.CharField(max_length=255, verbose_name='RG')),
                ('e_pcd', models.BooleanField(default=False, verbose_name='PCD')),
                ('possui_cnh', models.BooleanField(default=False, verbose_name='Possui CNH')),
                ('categoria', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=255, null=True, verbose_name='Categoria')),
                ('e_primeiro_emprego', models.BooleanField(default=False, verbose_name='Primeiro Emprego')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('informacoes_adicionais', models.TextField(verbose_name='Informações Adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('area_de_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.areainteresse', verbose_name='Área de Interesse')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('data_de_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_de_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curriculo', verbose_name='Currículo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curriculo', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(max_length=255, verbose_name='Grau')),
                ('curso', models.CharField(max_length=255, verbose_name='Curso')),
                ('data_de_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_de_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curriculo', verbose_name='Currículo')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Inglês', 'Inglês'), ('Espanhol', 'Espanhol'), ('Francês', 'Francês'), ('Alemão', 'Alemão'), ('Italiano', 'Italiano'), ('Mandarim', 'Mandarim'), ('Japonês', 'Japonês'), ('Russo', 'Russo'), ('Coreano', 'Coreano'), ('Árabe', 'Árabe'), ('Hebraico', 'Hebraico'), ('Hindi', 'Hindi'), ('Outro', 'Outro')], max_length=255, verbose_name='Idioma')),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Fluente', 'Fluente')], max_length=255, verbose_name='Nível')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('complemento', models.CharField(max_length=255, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=255, verbose_name='Estado')),
                ('cep', models.CharField(max_length=255, verbose_name='CEP')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='SubareaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('area_de_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areainteresse', verbose_name='Área de Interesse')),
            ],
            options={
                'verbose_name': 'Subárea de Interesse',
                'verbose_name_plural': 'Subáreas de Interesse',
            },
        ),
        migrations.AddField(
            model_name='curriculo',
            name='subarea_de_interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subareainteresse', verbose_name='Subárea de Interesse'),
        ),
    ]
