# Generated by Django 5.0.6 on 2024-06-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='area_de_interesse',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='subarea_de_interesse',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='subareas_de_interesse',
            field=models.ManyToManyField(to='app.subareainteresse', verbose_name='Subáreas de Interesse'),
        ),
    ]
