# Generated by Django 5.0.6 on 2024-07-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_endereco_endereco_remove_pessoa_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Empregado ou não'),
        ),
    ]
