# Generated by Django 5.0.6 on 2024-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_curriculo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idioma',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='idiomas',
            field=models.ManyToManyField(to='app.idioma', verbose_name='Idiomas'),
        ),
    ]
